version: '3'
services:
  maze:
    image: wuhanstudio/maze-2.5d:latest
    networks:
     - traefik_public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.maze.rule=Host(`maze.${ROOT_DOMAIN}`)"
        - "traefik.http.routers.maze.entrypoints=web"
        - "traefik.http.services.maze.loadbalancer.server.port=80"
        # TLS
        - "traefik.http.routers.mazes.rule=Host(`maze.${ROOT_DOMAIN}`)"
        - "traefik.http.routers.mazes.entrypoints=websecure"
        - "traefik.http.routers.mazes.tls.certresolver=myhttpchallenge"
        # Redirect
        - "traefik.http.routers.maze.middlewares=https_redirect"
        - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
networks:
  traefik_public:
    external: true

