version: '3'
services:
  helloworld:
    image: nginxdemos/hello:0.4
    networks:
      - traefik_public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.helloworld.rule=Host(`${HELLO_NAME}.${ROOT_DOMAIN}`)"
        - "traefik.http.routers.helloworld.entrypoints=web"
        - "traefik.http.services.helloworld.loadbalancer.server.port=80"
        # TLS
        - "traefik.http.routers.helloworlds.rule=Host(`${HELLO_NAME}.${ROOT_DOMAIN}`)"
        - "traefik.http.routers.helloworlds.entrypoints=websecure"
        - "traefik.http.routers.helloworlds.tls.certresolver=myhttpchallenge"
        # Redirect
        - "traefik.http.routers.helloworld.middlewares=https_redirect"
        - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
networks:
  traefik_public:
    external: true

