# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  ROOT_DOMAIN_VAR: wuhanstudio.click

env:
  ROOT_DOMAIN: '{{.ROOT_DOMAIN_VAR}}'

tasks:
  hello:
    desc: Install helloworld application
    cmds:
      - docker stack deploy -c hello-compose.yml hello

  status:
    desc: Check deployment status
    cmds:
      - docker stack ls
      - docker service ls
      - sudo cat ./letsencrypt/acme.json | grep {{.ROOT_DOMAIN_VAR}}

  uninstall:
    desc: Uninstall helloworld application
    cmds:
      - docker stack rm hello
