# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  LETSENCRYPT_DIR_VAR: /mnt/letsencrypt
  ROOT_DOMAIN_VAR: wuhanstudio.click
  HELLO_NAME_VAR: hello

env:
  ROOT_DOMAIN: '{{.ROOT_DOMAIN_VAR}}'

tasks:
  hello:
    desc: Install helloworld application
    env:
      HELLO_NAME: '{{.HELLO_NAME_VAR}}'
    cmds:
      - docker stack deploy -c hello-compose.yml hello

  status:
    desc: Check deployment status
    cmds:
      - docker stack ls
      - docker service ls
      - sudo cat {{.LETSENCRYPT_DIR_VAR}}/acme.json | grep {{.ROOT_DOMAIN_VAR}}

  uninstall:
    desc: Uninstall helloworld application
    cmds:
      - docker stack rm hello
